### ISSUE TITLE
consider using krew-release-bot for auto releasing allctx plugin on krew

### ISSUE THREAD

**Issue by rajatjindal** [onatm/kall#1]
Hi

I manage krew-release-bot, a bot to automatically do version bump PR with krew-index repo once new release is made.

request you to kindly consider including the bot in your release process. FYI, it does not require any credentials as such to work.

a sample PR: kubernetes-sigs/krew-index#1271

Thanks
Rajat Jindal

**Comment by onatm** [comment]
Thank you for letting me know about your bot. I don't think this plugin will ever need to be updated.
